version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: python-backend
    ports:
      - "8000:8000"
    volumes:
      - .env:/app/.env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  
